ktor:
  deployment:
    port: 8081
  application:
    modules:
      - com.hivestudio.server.ApplicationKt.module

database:
  jdbcUrl: "jdbc:postgresql://localhost:5432/hive_studio"
  user: "matthew"
  password: ""
  connectOnStartup: true
  showSql: false

storage:
  uploadDir: "./storage/uploads"
